WITH LOOKUP AS (
    SELECT DET_ID, LOOKUP_DET_NAME, IDS
    FROM AB_LOOKUP_DETAIL
    WHERE STATUS = 'Y'
),
REGISTRATION AS (
    SELECT SR_ID, REG_NAME, PARTY_NAME
    FROM AB_SETUP_REGISTRATION
    WHERE REG_STATUS = 'Y'
),
SALE_INVOICE_DETAIL AS (
    SELECT 
 ASOH.SO_ID, ASO.CREATED_ON , ASO.SO_TYPE
FROM 
     AB_SO_ORDER_HEAD ASO                       -- SALE INVOICE
JOIN AB_SO_ORDER_HEAD ASOB ON ASOB.SO_ID = ASO.SO_IDS    -- SO DISPATCHED
JOIN AB_SO_ORDER_HEAD  ASOC ON ASOC.SO_ID = ASOB.SO_IDS   -- SALE PENDING LOADING
JOIN AB_SO_ORDER_HEAD ASOD ON ASOD.SO_ID = ASOC.SO_IDS   -- SALE PENDING
JOIN AB_SO_ORDER_DET DET ON DET.SO_ID = ASOD.SO_ID 
JOIN AB_SO_ORDER_DET DETS ON  DETS.SOD_ID = DET.SOD_IDS
JOIN AB_SO_ORDER_HEAD ASOH ON ASOH.SO_ID = DETS.SO_ID
AND ASO.ORG_ID = :GV_ORG_ID
)

SELECT 
    SO.SO_ID,
    SOD.SOD_ID,
    CU.SR_ID,
    SO.SO_TYPE,
    USER_NAME AS SALE_OFFER,
    SO.CITY AS CITY,
    SO.ORDER_DATE AS ORDER_DATE,
    INITCAP(ST.LOOKUP_DET_NAME) AS STOCK_TYPE,
    INITCAP(STK.LOOKUP_DET_NAME) AS STOCK_WISE,
    CU.REG_NAME AS PARTY_NAME,
    CP.REG_NAME AS COMPANY_NAME,
    WAR.REG_NAME AS FROM_WAREHOUSE,
    SOD.WAREHOUSE_ID,
    FT.LOOKUP_DET_NAME AS FREIGHT_TYPE,
    DS.LOOKUP_DET_NAME AS DELIVERY_STATUS,
    PY.LOOKUP_DET_NAME AS PAYMENT_MODE,
    SOD.ITEM_ID,
    ITM.ITEM_NAME || ' ' || ITM.PACKING_SIZE || '(' || ITM.UNIT || ') ' || PACKING AS PRODUCT_NAME,
    SOD.NO_BAGS,
    SOD.BAG_RATE,
    SOD.TOTAL_AMOUNT,
    SO.RECOVERY_STATUS,
    INITCAP(SO.CREATED_BY || ' (' || TO_CHAR(SO.CREATED_ON, 'DD-MON-YYYY') || ')') AS CREATED_BY,
    SO.CREATED_ON,
    TO_CHAR(SI.CREATED_ON , 'DD-MON-YYYY') AS INVOICE_DATE,

                CASE 
                WHEN PY.LOOKUP_DET_NAME = 'WITHOUT ANY CONDITION' 
                THEN TO_CHAR(SO.ORDER_DATE, 'DD-MON-YYYY')
                WHEN PY.LOOKUP_DET_NAME = '1st WORKING DAY PAYMENT'
                THEN TO_CHAR(NEXT_DAY(SO.ORDER_DATE, 'MONDAY'), 'DD-MON-YYYY')
                WHEN PY.LOOKUP_DET_NAME = 'DATE OF PAYMENT'
                THEN TO_CHAR(TRUNC(SYSDATE),'DD-MON-YYYY')
                WHEN PY.LOOKUP_DET_NAME = 'TODAY'
                THEN TO_CHAR(SO.ORDER_DATE, 'DD-MON-YYYY')
                WHEN PY.LOOKUP_DET_NAME = 'PAYMENT ON DELIVERY'
                THEN TO_CHAR(SI.CREATED_ON, 'DD-MON-YYYY')
                ELSE NULL
               END AS DUE_DATE,

    TRUNC(SYSDATE) - 
(
    CASE 
        WHEN PY.LOOKUP_DET_NAME = 'WITHOUT ANY CONDITION' 
            THEN SO.ORDER_DATE
        WHEN PY.LOOKUP_DET_NAME = '1st WORKING DAY PAYMENT'
            THEN NEXT_DAY(SO.ORDER_DATE, 'MONDAY')
        WHEN PY.LOOKUP_DET_NAME = 'DATE OF PAYMENT'
            THEN TRUNC(SYSDATE)
        WHEN PY.LOOKUP_DET_NAME = 'TODAY'
            THEN SO.ORDER_DATE
           WHEN PY.LOOKUP_DET_NAME = 'PAYMENT ON DELIVERY'
           THEN TRUNC(SI.CREATED_ON)
        ELSE NULL
    END
) ||' '||'Days' AS OVERDUE_AGING


FROM AB_SO_ORDER_HEAD SO
JOIN AB_SO_ORDER_DET SOD  ON SOD.SO_ID = SO.SO_ID 
    AND SOD.STATUS = 'Y'
JOIN AB_ITEMS_MASTER ITM 
    ON ITM.ITEM_ID = SOD.ITEM_ID 
    AND ITM.STATUS = 'Y'
LEFT JOIN LOOKUP FT 
    ON FT.DET_ID = SO.FREIGHT_TYPE_ID 
LEFT JOIN LOOKUP DS 
    ON DS.DET_ID = SO.DELIVERY_STATUS
LEFT JOIN LOOKUP PY 
    ON PY.DET_ID = SO.PAYMENT_ID
LEFT JOIN REGISTRATION WAR 
    ON WAR.SR_ID = SOD.WAREHOUSE_ID
LEFT JOIN REGISTRATION CU 
    ON CU.SR_ID = SO.CUSTOMER_ID
LEFT JOIN REGISTRATION CP 
    ON CP.SR_ID = SO.COMPANY_ID
LEFT JOIN LOOKUP STK 
    ON STK.DET_ID = SOD.STOCK_CATEGORY_ID
LEFT JOIN LOOKUP ST 
    ON ST.DET_ID = STK.IDS
LEFT JOIN AB_UM_APPLICATION_USERS UM  
    ON UM.USER_ID = SO.SALE_OFFER_ID
LEFT JOIN SALE_INVOICE_DETAIL SI ON SI.SO_ID = SO.SO_ID
WHERE SO.SO_TYPE IN ('SALE ORDER')
AND  ITM.ITEM_ID  = NVL(:P722_PRODUCT_ID,ITM.ITEM_ID)
AND CU.SR_ID = NVL(:P722_PARTY_NAME, CU.SR_ID)
  AND SO.ORG_ID = :GV_ORG_ID
 AND 
 SO.STATUS = 'Y'

        and
             TRUNC(SO.ORDER_DATE) BETWEEN NVL(TO_DATE(:P722_FROM_DATE, 'DD-MON-YYYY'), TRUNC(SO.ORDER_DATE))  AND NVL(TO_DATE(:P722_TO_DATE, 'DD-MON-YYYY'), TRUNC(SO.ORDER_DATE) )
